# Generated by Django 5.2.4 on 2025-10-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvacPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='evac_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField(help_text='Координата X в процентах (0–100)')),
                ('y', models.FloatField(help_text='Координата Y в процентах (0–100)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='map_api.evacplan')),
            ],
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='panoramas/')),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panorama', to='map_api.mappoint')),
            ],
        ),
        migrations.CreateModel(
            name='PanoramaMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimuth', models.FloatField(help_text='Угол (в градусах) направления на маркер')),
                ('pitch', models.FloatField(help_text='Угол (в градусах) по вертикали')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='map_api.panorama')),
                ('target_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_api.mappoint')),
            ],
        ),
    ]
