# Generated by Django 5.2.4 on 2026-01-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0002_add_floor_type_infotext_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaInfoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimuth', models.FloatField(help_text='Азимут направления на точку (0–360°)', verbose_name='Азимут')),
                ('pitch', models.FloatField(default=0, help_text='Угол по вертикали (-90..90°)', verbose_name='Угол наклона')),
                ('title', models.CharField(blank=True, default='', help_text='Короткая подпись (необязательно)', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default='', help_text='Текст информационной точки (показывается при наведении/клике)', verbose_name='Текст')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_points', to='map_api.panorama')),
            ],
            options={
                'verbose_name': 'Инфо-точка панорамы',
                'verbose_name_plural': 'Инфо-точки панорамы',
                'ordering': ['id'],
            },
        ),
    ]
