# Generated by Django 5.2.4 on 2026-02-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0002_add_floor_type_infotext_label'),
        ('map_api', '0003_panoramainfopoint'),
    ]

    operations = [
    ]
