# Generated by Django 5.2.4 on 2026-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0004_merge_20260208_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappoint',
            name='type',
        ),
        migrations.AddField(
            model_name='panoramamarker',
            name='type',
            field=models.CharField(choices=[('transition', 'Переходная (панорама)'), ('info', 'Информационная')], default='transition', max_length=20, verbose_name='Тип точки'),
        )
    ]
