# Generated by Django 5.2.4 on 2026-02-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0005_remove_mappoint_type_panoramamarker_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanoramaInfoPoint',
        ),
    ]
