# Generated by Django 5.2.4 on 2026-02-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0006_delete_panoramainfopoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoramamarker',
            name='target_point',
            field=models.ForeignKey(blank=True, help_text='Точка, на которую переходит панорама при нажатии на маркер', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_markers', to='map_api.mappoint', verbose_name='Целевая точка'),
        ),
    ]
