# Generated by Django 5.2.4 on 2026-02-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0008_panoramamarker_text_and_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='info_text',
            field=models.TextField(blank=True, default='', help_text='Текст для info-точки (отображается при наведении)', null=True, verbose_name='Информационный текст'),
        ),
    ]
