# Generated by Django 5.2.4 on 2026-04-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0011_tourinfomarkerview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCodeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, verbose_name='Кодовое слово')),
            ],
            options={
                'verbose_name': 'Кодовое слово регистрации',
                'verbose_name_plural': 'Кодовое слово регистрации',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='markers',
            field=models.ManyToManyField(blank=True, related_name='tours', through='map_api.TourMarker', to='map_api.panoramamarker'),
        ),
    ]
